name: ci-build

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'poetry'
      - run: poetry install --no-root
      - run: poetry run mkdocs build
