name: ci

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'poetry'
      - run: poetry install --no-interaction
      - run: poetry run mkdocs gh-deploy --force
